### PR TITLE
fix login redirect caching

### LINKED ISSUE #132: Caching of authenticated WP pages results in redirect loops / inconsistent behavior
Pages that require authentication are incorrectly cached by Kinsta.

For WP sites where the whole site is protected by bcc-login plugin, this may result in redirect loops for unauthenticated users - since the redirect response is cached.

A solution may be to redirect to a non-cached page before adding user specific parameters and redirecting to auth / login

### PR DESCRIPTION
**Pull request by JakubC-projects**
Fixes issue with cached login redirect responses by first always redirecting to wp_login.php which is never cached.

closes #132

### CODE REVIEW

File: plugins/bcc-login/includes/class-bcc-login-client.php [hunk 1]
```diff
@@ -273,9 +273,14 @@ private function get_current_url() {
 
         // If the Permalink Structure is set to Plain we use the old solution with $_SERVER
         // We replace 'wp-login.php' to 'wp-admin' to avoid the redirect loop when logging through SSO directly to the admin dashboard
-        return get_option('permalink_structure') == ""
-            ? $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST'] . str_replace('wp-login.php', 'wp-admin', $_SERVER['REQUEST_URI'])
-            : add_query_arg( $_SERVER['QUERY_STRING'], '', home_url( $wp->request ) );
+        if( get_option('permalink_structure') != "")
+            return add_query_arg( $_SERVER['QUERY_STRING'], '', home_url( $wp->request ) );
+        
+        if(isset($_GET['redirect_to']))
```
Comment (rvanoord) [inline plugins/bcc-login/includes/class-bcc-login-client.php:279]: Maybe we should check the domain here, so we don't support an open redirect?

**Review by rvanoord — APPROVED** [review]
